Document: python-ssh-ldap-pubkey
Title: Debian python-ssh-ldap-pubkey Manual
Author: <insert document author here>
Abstract: This manual describes what python-ssh-ldap-pubkey is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-ssh-ldap-pubkey/python-ssh-ldap-pubkey.sgml.gz

Format: postscript
Files: /usr/share/doc/python-ssh-ldap-pubkey/python-ssh-ldap-pubkey.ps.gz

Format: text
Files: /usr/share/doc/python-ssh-ldap-pubkey/python-ssh-ldap-pubkey.text.gz

Format: HTML
Index: /usr/share/doc/python-ssh-ldap-pubkey/html/index.html
Files: /usr/share/doc/python-ssh-ldap-pubkey/html/*.html
